# Generated by Django 2.2.2 on 2019-06-09 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PropietarioVehiculo',
            fields=[
                ('id_propietario_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propietario.Propietario')),
                ('vehiculo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Vehiculo')),
            ],
        ),
    ]
