# Generated by Django 2.2.2 on 2019-06-09 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ChoferVehiculo',
            fields=[
                ('id_chofer_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField()),
                ('chofer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chofer.Chofer')),
                ('vehiculo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoChofer',
            fields=[
                ('id_tipo_chofer', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tipo_chofer', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHorario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('num_licencia', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=2)),
                ('fec_expedicion', models.DateField()),
                ('fec_vencimiento', models.DateField()),
                ('oficia_expedida', models.CharField(max_length=30)),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chofer.Chofer')),
            ],
        ),
        migrations.CreateModel(
            name='ChoferVehiculoHorario',
            fields=[
                ('id_chofer_vehiculo_horario', models.AutoField(primary_key=True, serialize=False)),
                ('chofer_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chofer.ChoferVehiculo')),
                ('horario_turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chofer.TipoHorario')),
            ],
        ),
        migrations.AddField(
            model_name='chofer',
            name='tipo_chofer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chofer.TipoChofer'),
        ),
    ]
